#!/bin/bash
# AUTO-GENERATED BY UNIVERSAL CONTEXT HUB
TARGET="/Users/jpdouma/projects/yield-force"

if [ -d "$TARGET" ]; then
    echo "--- DIRECTORY STRUCTURE ($TARGET) ---"
    ls -la "$TARGET" | head -n 30
    echo ""
    echo "[Note: To add specific files to this payload, edit workspaces/yield-force/.context_script.sh]"
else
    echo "ERROR: Codebase path not found or invalid: $TARGET"
fi
echo -e "\n--- GIT STATUS ---"
git -C "$1" status -s

echo -e "\n--- GIT DIFF (UNCOMMITTED CHANGES) ---"
git -C "$1" diff
